export const ADVENTURES_TR = {
  explore: [
    {title:"Kayıp Sokak",description:"Hiç gitmediğin bir sokağa sap. 10 dakika boyunca GPS kullanmadan yürü.",tips:"Maps'i kapat! Kaybolmak keşfin başlangıcı.",xp:30,env:"outdoor"},
    {title:"Manzara Avcısı",description:"Bulunduğun bölgenin en yüksek noktasını bul ve oradan panoramik fotoğraf çek.",tips:"Teras, tepe veya üst kat dene.",xp:40,env:"outdoor"},
    {title:"Zaman Yolcusu",description:"Semtindeki en eski binayı bul ve tarihini araştır.",tips:"Kapı üstü tarihlere ve mimari detaylara bak!",xp:35,env:"outdoor"},
    {title:"Gizli Geçit",description:"Daha önce fark etmediğin bir ara sokak veya geçit bul.",tips:"Ana caddelerin arkasına dön.",xp:35,env:"outdoor"},
    {title:"Renk Avı",description:"Tek bir rengi 7 farklı tonda fotoğrafla.",tips:"Gökyüzü saymaz! Detaylarda ara.",xp:30,env:"outdoor"},
    {title:"Kapı Koleksiyoncusu",description:"En güzel, en ilginç 5 kapıyı fotoğrafla.",tips:"Eski mahalleler hazine dolu!",xp:30,env:"outdoor"},
    {title:"Harita Çizici",description:"15 dk rastgele yürü, sonra rotayı hafızadan kağıda çiz.",tips:"Dönüm noktalarını ve dikkat çekici yerleri hatırla.",xp:40,env:"outdoor"},
    {title:"Gece Kaşifi",description:"Gündüz gittiğin bir yeri gece ziyaret et, farkları not al.",tips:"Güvenli bölgede kal. Işıklar farklı bir atmosfer yaratır.",xp:45,env:"outdoor"},
    {title:"Çeşme Avcısı",description:"Bölgendeki tarihi çeşmeleri bul. En az 3 tane fotoğrafla.",tips:"Cami avluları ve eski mahalleler iyi başlangıç.",xp:35,env:"outdoor"},
    {title:"Pencere Kaşifi",description:"Evin her penceresinden dışarı fotoğraf çek ve bir kolaj yap.",tips:"Farklı saatlerde farklı ışık yakala.",xp:25,env:"home"},
    {title:"Google Earth Gezgini",description:"Rastgele bir kıtaya tıkla, Street View ile 10 dk sanal yürüyüş yap.",tips:"Güney Amerika ve Güneydoğu Asya ilginç yerler!",xp:25,env:"home"},
    {title:"Duvar Yazısı Avcısı",description:"Sokak sanatı veya ilginç duvar yazılarını fotoğrafla. En az 5 tane bul.",tips:"Üniversite çevreleri ve sanat mahalleleri ideal.",xp:35,env:"outdoor"},
    {title:"Tabela Dedektifi",description:"En eski veya en ilginç dükkan tabelasını bul.",tips:"El yazısı tabelalar özellikle değerli.",xp:30,env:"outdoor"},
    {title:"Semt Tarihçisi",description:"Oturduğun semtin tarihini araştır, 3 ilginç bilgi öğren.",tips:"Belediye sitesi veya Wikipedia iyi kaynak.",xp:35,env:"home"},
    {title:"Merdiven Haritacısı",description:"Semtindeki tüm merdivenleri bul ve fotoğrafla.",tips:"Yamaç semtleri merdiven cenneti!",xp:40,env:"outdoor"},
    {title:"Pazar Keşfi",description:"En yakın semt pazarına git, 3 tezgahla sohbet et.",tips:"Sabah erken git, en taze ürünler o zaman.",xp:35,env:"place"},
    {title:"Ağaç Kucaklayıcı",description:"Mahallendeki en büyük veya en yaşlı ağacı bul.",tips:"Ağacın türünü PlantNet ile öğren.",xp:30,env:"outdoor"},
    {title:"Sokak Müzesi",description:"Yürürken gördüğün 10 ilginç detayı fotoğrafla (kapı tokmağı, rögar kapağı vb).",tips:"Yere ve yukarı bakmayı unutma!",xp:35,env:"outdoor"},
    {title:"Mahalle Haritası",description:"Oturduğun mahallenin el çizimi haritasını yap.",tips:"Önemli noktaları ve gizli köşeleri işaretle.",xp:40,env:"home"},
    {title:"Köprü Avcısı",description:"Şehrindeki köprüleri keşfet, en az 2 tanesini fotoğrafla.",tips:"Her köprünün bir hikayesi var.",xp:35,env:"outdoor"}
  ],
  social: [
    {title:"Gülümseme Zinciri",description:"5 yabancıya samimi bir gülümseme gönder ve tepkilerini gözlemle.",tips:"Doğal göz teması kur, zorla değil.",xp:30,env:"outdoor"},
    {title:"Eski Dost",description:"6 aydır konuşmadığın birine mesaj at.",tips:"'Nasılsın?' bile yeterli. Samimi ol.",xp:35,env:"home"},
    {title:"Komşu Tanışması",description:"Hiç konuşmadığın bir komşuyla 3 dakikalık sohbet aç.",tips:"Hava durumu veya bina hakkında soru iyi başlangıç!",xp:40,env:"outdoor"},
    {title:"Teşekkür Turu",description:"Bugün 3 farklı kişiye spesifik bir teşekkür et.",tips:"'Her şey için' yerine neye teşekkür ettiğini söyle.",xp:35,env:"home"},
    {title:"Yeni İsim",description:"Bugün tanımadığın birinin adını öğren ve ismiyle hitap et.",tips:"Market kasiyeri, komşu, garson olabilir.",xp:30,env:"place"},
    {title:"Hikaye Dinleyici",description:"Yaşlı birine gençlik hikayesi sor, sözünü kesmeden dinle.",tips:"Parkta, kafede veya komşu olabilir.",xp:40,env:"any"},
    {title:"İltifat Maratonu",description:"5 kişiye kalıptan çıkmış, samimi iltifatlar et.",tips:"Dış görünüş yerine davranış veya enerji hakkında ol.",xp:30,env:"outdoor"},
    {title:"Aile Günü",description:"Aileden biriyle birlikte yeni bir aktivite yap.",tips:"Telefonlar kenarda! Tam odaklan.",xp:40,env:"home"},
    {title:"Rastgele Yardım",description:"Bugün fark ettiğin bir ihtiyaca yardım et (kapı tut, yol tarif et).",tips:"Fırsatlar her yerde, gözünü aç.",xp:35,env:"outdoor"},
    {title:"Sesli Mesaj Sürprizi",description:"3 kişiye beklenmedik bir sesli mesaj gönder.",tips:"Gülümserken kaydet, enerji bulaşıcıdır.",xp:30,env:"home"},
    {title:"Kahve Ikramı",description:"Tanımadığın birine çay veya kahve ısmarla.",tips:"Kafe kuyruğunda arkandakine ısmarla!",xp:45,env:"place"},
    {title:"Mektup Yaz",description:"Sevdiğin birine el yazısıyla kısa bir mektup yaz.",tips:"Zarfa koy, posta veya elden ver.",xp:40,env:"home"},
    {title:"Sokak Müzisyenine Dur",description:"Sokak müzisyenini en az 1 şarkı boyunca dinle, teşekkür et.",tips:"Gözlerini kapat ve müziği hisset.",xp:30,env:"outdoor"},
    {title:"Fotoğraf Çekme Teklifi",description:"Turistlere veya yoldan geçenlere fotoğraf çekmeyi teklif et.",tips:"Güler yüzle yaklaş, 'Fotoğrafınızı çekeyim mi?' de.",xp:35,env:"outdoor"},
    {title:"Çocukluk Arkadaşı",description:"Çocukluk arkadaşını bul ve ona ulaş.",tips:"Sosyal medya veya ortak tanıdıklar yardımcı olabilir.",xp:40,env:"home"},
    {title:"Takdir Notu",description:"İş yerinde veya okulda birine yazılı takdir notu bırak.",tips:"Post-it ile masasına bırak, imzala veya anonim.",xp:35,env:"place"},
    {title:"Yeni Arkadaş",description:"Bugün en az 1 yeni insanla tanış ve iletişim bilgisi al.",tips:"Ortak ilgi alanları sor.",xp:45,env:"outdoor"},
    {title:"Aile Fotoğrafı",description:"Ailece veya arkadaşlarla toplu bir fotoğraf çek.",tips:"Timer kullan, herkes hazır olana kadar bekle.",xp:30,env:"home"},
    {title:"Komşuya İkram",description:"Komşuna ev yapımı bir şey götür (kurabiye, kek).",tips:"Basit bir tarif bile çok anlamlı.",xp:45,env:"home"},
    {title:"Teşekkür Videosu",description:"Seni etkileyen birine 30 saniyelik teşekkür videosu çek ve gönder.",tips:"Doğal ol, mükemmel olmak zorunda değil.",xp:40,env:"home"}
  ],
  creative: [
    {title:"60 Saniye Sanat",description:"Önündeki herhangi bir nesneyi 60 saniyede çiz.",tips:"Telefon uygulaması veya kağıt-kalem, fark etmez!",xp:30,env:"home"},
    {title:"Hikaye Avcısı",description:"Etrafındaki 3 rastgele nesneden 5 cümlelik bir hikaye yaz.",tips:"Ne kadar alakasız olursa o kadar eğlenceli.",xp:35,env:"home"},
    {title:"Ses Kolajı",description:"5 farklı ilginç sesi kaydet ve bir ses kolajı oluştur.",tips:"Her kayıt 10 sn yeterli. Doğa + şehir karıştır.",xp:35,env:"outdoor"},
    {title:"Gölge Sanatçısı",description:"3 ilginç gölge yakala ve fotoğrafla.",tips:"Öğle saati en dramatik gölgeleri yaratır.",xp:30,env:"outdoor"},
    {title:"Haiku Yazarı",description:"3 haiku yaz (5-7-5 hece kuralıyla).",tips:"O anı, o duyguyu yakala. Basitlik güçtür.",xp:35,env:"home"},
    {title:"Müzik Dedektifi",description:"Kafede, markette duyduğun şarkıyı Shazam'la ve tam albümünü dinle.",tips:"Yeni müzik keşfi en güzel keşiftir.",xp:30,env:"place"},
    {title:"Fotoğraf Hikayesi",description:"5 fotoğrafla başı-sonu olan bir hikaye anlat.",tips:"Kronolojik sıra şart değil.",xp:40,env:"outdoor"},
    {title:"Sol El Denemesi",description:"Diğer elinle bir resim çiz veya bir paragraf yaz.",tips:"Gül ve devam et! Sonuç önemli değil.",xp:35,env:"home"},
    {title:"Doğa Kolajı",description:"Yaprak, taş, çiçekle yere bir kompozisyon oluştur ve fotoğrafla.",tips:"Simetri ve kontrast güzel sonuç verir.",xp:40,env:"outdoor"},
    {title:"Spotify Macerası",description:"Spotify Keşfet'te 3 farklı türde şarkı dinle.",tips:"Her şarkıya en az 1 dk şans ver.",xp:25,env:"home"},
    {title:"Mini Film",description:"Telefonla 30 saniyelik kısa film çek.",tips:"Basit bir senaryo düşün: başlangıç, gelişme, son.",xp:45,env:"any"},
    {title:"Şiir Yazarı",description:"Bugün yaşadığın bir anı 4 satırlık şiir yap.",tips:"Kafiye zorunlu değil, duygu önemli.",xp:35,env:"home"},
    {title:"Yemek Fotoğrafçısı",description:"Bugünkü yemeğini profesyonel gibi fotoğrafla.",tips:"Doğal ışık, 45 derece açı, temiz arka plan.",xp:25,env:"home"},
    {title:"Kolaj Sanatçısı",description:"Eski dergi, gazete veya baskılardan bir kolaj yap.",tips:"Tema belirle: doğa, şehir, duygular.",xp:40,env:"home"},
    {title:"Sokak Fotoğrafçısı",description:"Henri Cartier-Bresson gibi 'karar anı' yakala. 10 fotoğraf çek.",tips:"Sabırlı ol, anı bekle.",xp:40,env:"outdoor"},
    {title:"Origami Ustası",description:"YouTube'dan bir origami öğren ve yap.",tips:"Turna kuşu klasik başlangıç!",xp:35,env:"home"},
    {title:"Playlist Yapımcısı",description:"Bir tema seç ve 10 şarkılık playlist oluştur.",tips:"'Yağmurlu gün', 'motivasyon', 'gece yürüyüşü' gibi.",xp:30,env:"home"},
    {title:"Minyatür Dünya",description:"Küçük nesnelerle minyatür bir sahne oluştur ve fotoğrafla.",tips:"Yakın çekim ve düşük açı büyüsü yaratır.",xp:40,env:"home"},
    {title:"Günlük Çizim",description:"Bugünü temsil eden tek bir çizim yap.",tips:"Stick figure bile olur! Önemli olan anlamı.",xp:30,env:"home"},
    {title:"Ses Manzarası",description:"Bulunduğun yerin 1 dakikalık ses kaydını al.",tips:"Gözlerini kapat, ne duyduğunu not et.",xp:30,env:"outdoor"}
  ],
  mindful: [
    {title:"5 Duyu Meditasyonu",description:"5 şey gör, 4 şeye dokun, 3 şey duy, 2 şey kokla, 1 şey tat.",tips:"Başlamadan 3 derin nefes al.",xp:30,env:"any"},
    {title:"Dijital Detox",description:"1 saat telefonu uçak moduna al. Hiç ekrana bakma.",tips:"Telefonu başka odaya bırak.",xp:40,env:"home"},
    {title:"Şükran Mektubu",description:"Minnettar olduğun birine samimi bir mektup yaz.",tips:"El yazısı daha anlamlı ve kişisel.",xp:35,env:"home"},
    {title:"Bulut Seyri",description:"15 dk gökyüzüne bak, bulutlarda şekiller bul.",tips:"Çimenlere uzan, telefonu bırak.",xp:30,env:"outdoor"},
    {title:"Sessiz Yürüyüş",description:"20 dk kulaklıksız, müziksiz yürü. Sadece çevreyi dinle.",tips:"Her adımı hisset. Bu bir yürüyüş meditasyonu.",xp:35,env:"outdoor"},
    {title:"Nefes Sayacı",description:"5 dk boyunca nefeslerini say. 100'e ulaşmaya çalış.",tips:"Zihnin kayarsa, nazikçe geri getir.",xp:30,env:"home"},
    {title:"Günlük Tek Sayfa",description:"Bugünü filtre olmadan tek sayfaya yaz.",tips:"Dürüst ol. Kimse okumayacak.",xp:35,env:"home"},
    {title:"Yavaş Yemek",description:"Bir öğünü 30 dakikada ye. Her lokmayı 20 kez çiğne.",tips:"Telefon ve TV kapalı. Sadece yemek ve sen.",xp:40,env:"home"},
    {title:"Gün Batımı Ritüeli",description:"Gün batımını baştan sona izle, o anı hisset.",tips:"Yüksek yer + sıcak bir içecek = mükemmel.",xp:35,env:"outdoor"},
    {title:"Vücut Taraması",description:"10 dk boyunca ayak ucundan başa her bölgeyi tara.",tips:"YouTube'da 'body scan meditation' ara.",xp:30,env:"home"},
    {title:"Minnettarlık Listesi",description:"Bugün minnettar olduğun 10 şeyi yaz.",tips:"Küçük şeyler de sayılır: sıcak bir çay, güneş.",xp:30,env:"home"},
    {title:"Doğa Banyosu",description:"30 dk doğada ol. Parkta otur, ağaçlara bak, kuşları dinle.",tips:"Japonların 'shinrin-yoku' tekniği bu!",xp:40,env:"outdoor"},
    {title:"Sabah Sayfaları",description:"Sabah kalkar kalkmaz 3 sayfa düşünceni yaz.",tips:"Düzenleme yapma, akışına bırak.",xp:35,env:"home"},
    {title:"Tek Görev Saati",description:"1 saat boyunca sadece tek bir işe odaklan. Multitasking yok.",tips:"Telefonu sessize al, bildirimleri kapat.",xp:40,env:"home"},
    {title:"Çay Seremonisi",description:"Çayını özenle demle, kokla, yudumla. Her adımı bilinçli yap.",tips:"En sevdiğin kupayı kullan.",xp:30,env:"home"},
    {title:"Yıldız Seyri",description:"Gece gökyüzüne 10 dk bak. Takımyıldızlarını bulmaya çalış.",tips:"Şehir ışıklarından uzak bir yer ideal.",xp:35,env:"outdoor"},
    {title:"Beden Teşekkürü",description:"Vücudunun her bölümüne zihinsel teşekkür et.",tips:"'Ellerime teşekkürler, bugün çok şey yaptılar.'",xp:30,env:"home"},
    {title:"Toprak Temas",description:"Çıplak ayakla çimlere veya toprağa bas. 5 dk dur.",tips:"'Grounding' tekniği: doğayla bağlan.",xp:35,env:"outdoor"},
    {title:"Sessizlik Zamanı",description:"15 dk boyunca hiçbir şey yapma. Sadece otur ve var ol.",tips:"Zor gelecek ama çok faydalı.",xp:40,env:"home"},
    {title:"Rüya Günlüğü",description:"Bugün uyandığında hatırladığın rüyayı yaz.",tips:"Uyanır uyanmaz yaz, hızla unutulur.",xp:25,env:"home"}
  ],
  food: [
    {title:"Bilinmeyen Lezzet",description:"Markette hiç denemediğin bir ürün al ve dene.",tips:"Egzotik meyveler, farklı soslar, yeni baharatlar!",xp:30,env:"outdoor"},
    {title:"Aşçı Modu",description:"Buzdolabındaki malzemelerle tarifsiz, spontan bir yemek yap.",tips:"Baharat çekmecen en iyi dostun.",xp:40,env:"home"},
    {title:"Kahve Ritüeli",description:"Kahveni özenle, adım adım hazırla. Her aşamanın tadını çıkar.",tips:"Türk kahvesi, french press veya V60 dene.",xp:30,env:"home"},
    {title:"Sokak Lezzeti",description:"Sokak satıcısından hiç denemediğin bir şey al.",tips:"Atmosferi hisset, satıcıyla sohbet et.",xp:30,env:"outdoor"},
    {title:"Dünya Mutfağı",description:"Bugün farklı bir ülke mutfağından yemek dene.",tips:"Hint, Tayland, Kore, Meksika, Japon!",xp:40,env:"place"},
    {title:"Çocukluk Lezzeti",description:"Çocukken en sevdiğin yemeği kendin yap.",tips:"Annene/babana tarifi sor!",xp:35,env:"home"},
    {title:"Sıfır Atık Şef",description:"Bitecek malzemelerle yaratıcı bir yemek yap.",tips:"Çorba, omlet ve makarna kurtarıcıdır.",xp:35,env:"home"},
    {title:"Tatlı Deney",description:"Daha önce yapmadığın basit bir tatlı dene.",tips:"Mug cake 5 dakikada hazır!",xp:35,env:"home"},
    {title:"Baharat Macerası",description:"Hiç kullanmadığın bir baharatla yemek yap.",tips:"Zerdeçal, kimyon, sumak, zencefil dene.",xp:30,env:"home"},
    {title:"Çay Degustasyonu",description:"3 farklı çay demle, aroma ve tatlarını karşılaştır.",tips:"Küçük fincanlar kullan, not al.",xp:25,env:"home"},
    {title:"Smoothie Sanatçısı",description:"3+ malzemeyle yaratıcı bir smoothie yap.",tips:"Muz + ıspanak + mango = başlangıç seviyesi.",xp:30,env:"home"},
    {title:"Ekmek Yapımcısı",description:"Evde basit bir ekmek veya pide yap.",tips:"Un, su, maya, tuz. Bu kadar basit!",xp:45,env:"home"},
    {title:"Piknik Hazırlığı",description:"Evde piknik sepeti hazırla, parkta veya balkonda ye.",tips:"Sandviç, meyve, çerez ve bir termos çay.",xp:35,env:"outdoor"},
    {title:"Kahvaltı Şefi",description:"Normalde yapmadığın lüks bir kahvaltı hazırla.",tips:"Yumurta benedict, pancake veya açma dene.",xp:35,env:"home"},
    {title:"Sos Ustası",description:"Sıfırdan bir sos yap (pesto, salsa, hummus vb).",tips:"Blender veya havanda dövme, ikisi de olur.",xp:35,env:"home"},
    {title:"Fermente Macera",description:"Turşu, yoğurt veya ekşi maya başlat.",tips:"En basiti: salatalık turşusu. Su + tuz + salatalık.",xp:40,env:"home"},
    {title:"Yemek Fotoğrafı",description:"Bugünkü yemeğini Instagram'a layık fotoğrafla.",tips:"Doğal ışık + beyaz arka plan + yakın çekim.",xp:25,env:"home"},
    {title:"Çikolata Degustasyonu",description:"3 farklı çikolata dene (bitter, sütlü, beyaz). Not al.",tips:"Kakao oranlarını karşılaştır.",xp:30,env:"home"},
    {title:"Uluslararası Atıştırma",description:"Markette yabancı bir atıştırmalık bul ve dene.",tips:"Asya marketleri hazine dolu!",xp:30,env:"outdoor"},
    {title:"Limonata Ustası",description:"Klasik olmayan bir limonata yap (lavanta, nane, zencefil).",tips:"Taze malzeme fark yaratır.",xp:30,env:"home"}
  ],
  fitness: [
    {title:"1000 Adım Ekstra",description:"Bugünkü adımlarına 1000 adım daha ekle.",tips:"Öğle molasında 15 dk yürüyüş yeterli.",xp:30,env:"outdoor"},
    {title:"Park Jimnastiği",description:"Parkta 10 şınav, 20 squat, 30 sn plank yap.",tips:"Park bankını kullan!",xp:40,env:"outdoor"},
    {title:"Esneme Seansı",description:"15 dk boyunca tüm vücudu esnet.",tips:"YouTube'da '15 min full body stretch' ara.",xp:30,env:"home"},
    {title:"Dans Partisi",description:"En sevdiğin 3 şarkıyı aç ve çılgınca dans et!",tips:"Perdeleri kapat, kimse görmüyor!",xp:35,env:"home"},
    {title:"Merdiven Tırmanıcı",description:"Asansör yerine merdiven kullan. En az 10 kat çık.",tips:"Adım sayar ile takip et.",xp:40,env:"outdoor"},
    {title:"7 Dakika Egzersiz",description:"Bilimsel 7 dakika HIIT programı yap.",tips:"Sadece 7 dk ama etkisi saatlerce sürer!",xp:35,env:"home"},
    {title:"Yürüyüş Buluşması",description:"Bir arkadaşını yürüyüşe çağır. Hem sohbet hem spor.",tips:"30 dk yeterli, kafe molası bonus!",xp:35,env:"outdoor"},
    {title:"Sabah Rutini",description:"Yarın sabah alarm kurup 5 dk egzersiz yap.",tips:"10 squat, 10 jumping jack, 10 lunge.",xp:40,env:"home"},
    {title:"Denge Ustası",description:"Tek ayakta 30 sn dur. İki tarafı da dene.",tips:"Bir noktaya odaklan, denge gelir.",xp:30,env:"home"},
    {title:"Ev Turu Koşusu",description:"5 dk boyunca evde durmadan hareket et.",tips:"Hafif tempo, müzik aç!",xp:30,env:"home"},
    {title:"Bisiklet Turu",description:"30 dk bisiklet sür. Rotayı önceden planla.",tips:"Bisikletin yoksa kiralama istasyonlarına bak.",xp:45,env:"outdoor"},
    {title:"Yoga Başlangıç",description:"YouTube'dan 15 dk başlangıç yogası yap.",tips:"'Yoga with Adriene' harika bir kaynak.",xp:35,env:"home"},
    {title:"Koşu Denemesi",description:"5 dk koş, 2 dk yürü. 3 set tekrarla.",tips:"Başlangıç için mükemmel tempo.",xp:40,env:"outdoor"},
    {title:"Ip Atlama",description:"100 kez ip atla. Mola vererek de olur.",tips:"İp yoksa hayali ip atla, ciddi!",xp:35,env:"home"},
    {title:"Plank Challenge",description:"Toplam 3 dk plank yap. Molalarla böl.",tips:"30 sn plank + 15 sn mola x 4 set.",xp:35,env:"home"},
    {title:"Yüzme",description:"Havuza veya denize git, 30 dk yüz.",tips:"Serbest stil + sırt üstü karıştır.",xp:45,env:"place"},
    {title:"Duvar Oturuşu",description:"Sırtın duvarda, 1 dk duvar oturuşu yap.",tips:"Dizler 90 derece, sırt düz.",xp:30,env:"home"},
    {title:"Akşam Yürüyüşü",description:"Akşam yemeğinden sonra 20 dk yürüyüş yap.",tips:"Sindirime ve uykuya çok iyi gelir.",xp:30,env:"outdoor"},
    {title:"Spor Dersi",description:"YouTube'dan yeni bir spor videosu dene (kickbox, pilates vb).",tips:"İlk seferde mükemmel olmak zorunda değilsin.",xp:40,env:"home"},
    {title:"Doğa Yürüyüşü",description:"En yakın doğa alanında 45+ dk yürüyüş yap.",tips:"Su ve atıştırmalık götür!",xp:45,env:"outdoor"}
  ]
};

export const ADVENTURES_EN = {
  explore: [
    {title:"Lost Street",description:"Turn into a street you've never been to. Walk for 10 minutes without GPS.",tips:"Turn off Maps! Getting lost is the start of discovery.",xp:30,env:"outdoor"},
    {title:"Viewpoint Hunter",description:"Find the highest point in your area and take a panoramic photo.",tips:"Try rooftops, hills, or upper floors.",xp:40,env:"outdoor"},
    {title:"Time Traveler",description:"Find the oldest building in your neighborhood and research its history.",tips:"Look for dates above doorways and architectural details!",xp:35,env:"outdoor"},
    {title:"Secret Passage",description:"Find an alley or passage you never noticed before.",tips:"Turn behind main streets.",xp:35,env:"outdoor"},
    {title:"Color Hunt",description:"Photograph a single color in 7 different shades.",tips:"Sky doesn't count! Look in the details.",xp:30,env:"outdoor"},
    {title:"Door Collector",description:"Photograph the 5 most beautiful or interesting doors.",tips:"Old neighborhoods are treasure troves!",xp:30,env:"outdoor"},
    {title:"Map Maker",description:"Walk randomly for 15 min, then draw the route from memory.",tips:"Remember landmarks and eye-catching spots.",xp:40,env:"outdoor"},
    {title:"Night Explorer",description:"Visit a place you went to during the day, but at night.",tips:"Stay in safe areas. Lights create a different atmosphere.",xp:45,env:"outdoor"},
    {title:"Fountain Hunter",description:"Find historic fountains in your area. Photograph at least 3.",tips:"Mosque courtyards and old neighborhoods are great starts.",xp:35,env:"outdoor"},
    {title:"Window Explorer",description:"Take a photo from every window in your home and make a collage.",tips:"Different times of day give different light.",xp:25,env:"home"},
    {title:"Google Earth Explorer",description:"Click on a random continent, do a 10-min virtual walk on Street View.",tips:"South America and Southeast Asia are fascinating!",xp:25,env:"home"},
    {title:"Street Art Hunter",description:"Find and photograph street art or interesting graffiti. At least 5.",tips:"University areas and art districts are ideal.",xp:35,env:"outdoor"},
    {title:"Sign Detective",description:"Find the oldest or most interesting shop sign.",tips:"Handwritten signs are especially valuable.",xp:30,env:"outdoor"},
    {title:"Local Historian",description:"Research the history of your neighborhood. Learn 3 interesting facts.",tips:"City website or Wikipedia are good sources.",xp:35,env:"home"},
    {title:"Stairway Mapper",description:"Find all the staircases in your area and photograph them.",tips:"Hillside neighborhoods are staircase heaven!",xp:40,env:"outdoor"},
    {title:"Market Discovery",description:"Go to the nearest farmers market, chat with 3 vendors.",tips:"Go early morning for the freshest products.",xp:35,env:"place"},
    {title:"Tree Hugger",description:"Find the biggest or oldest tree in your neighborhood.",tips:"Use PlantNet to identify the species.",xp:30,env:"outdoor"},
    {title:"Street Museum",description:"Photograph 10 interesting details while walking (knockers, manhole covers, etc).",tips:"Don't forget to look down and up!",xp:35,env:"outdoor"},
    {title:"Neighborhood Map",description:"Draw a hand-made map of your neighborhood.",tips:"Mark important spots and hidden corners.",xp:40,env:"home"},
    {title:"Bridge Hunter",description:"Explore bridges in your city, photograph at least 2.",tips:"Every bridge has a story.",xp:35,env:"outdoor"}
  ],
  social: [
    {title:"Smile Chain",description:"Send a genuine smile to 5 strangers and observe their reactions.",tips:"Make natural eye contact, don't force it.",xp:30,env:"outdoor"},
    {title:"Old Friend",description:"Text someone you haven't talked to in 6 months.",tips:"'How are you?' is enough. Be genuine.",xp:35,env:"home"},
    {title:"Neighbor Meet",description:"Start a 3-minute conversation with a neighbor you've never spoken to.",tips:"Weather or building topics are good openers!",xp:40,env:"outdoor"},
    {title:"Thank You Tour",description:"Thank 3 different people for something specific today.",tips:"Say exactly what you're thankful for.",xp:35,env:"home"},
    {title:"New Name",description:"Learn the name of someone you don't know and address them by it.",tips:"Could be a cashier, neighbor, or waiter.",xp:30,env:"place"},
    {title:"Story Listener",description:"Ask an elderly person about their youth. Listen without interrupting.",tips:"Could be at a park, café, or a neighbor.",xp:40,env:"any"},
    {title:"Compliment Marathon",description:"Give 5 sincere, non-generic compliments to people.",tips:"Focus on behavior or energy, not appearance.",xp:30,env:"outdoor"},
    {title:"Family Day",description:"Do a new activity together with a family member.",tips:"Phones away! Full focus.",xp:40,env:"home"},
    {title:"Random Help",description:"Help someone with something you notice today.",tips:"Opportunities are everywhere, keep your eyes open.",xp:35,env:"outdoor"},
    {title:"Voice Message Surprise",description:"Send unexpected voice messages to 3 people.",tips:"Smile while recording, energy is contagious.",xp:30,env:"home"},
    {title:"Coffee Treat",description:"Buy tea or coffee for a stranger.",tips:"Treat the person behind you in the café queue!",xp:45,env:"place"},
    {title:"Write a Letter",description:"Write a short handwritten letter to someone you love.",tips:"Put it in an envelope, mail or hand-deliver it.",xp:40,env:"home"},
    {title:"Street Musician Stop",description:"Listen to a street musician for at least 1 full song.",tips:"Close your eyes and feel the music.",xp:30,env:"outdoor"},
    {title:"Photo Offer",description:"Offer to take photos for tourists or passersby.",tips:"Approach with a smile: 'Want me to take your photo?'",xp:35,env:"outdoor"},
    {title:"Childhood Friend",description:"Find a childhood friend and reach out.",tips:"Social media or mutual friends can help.",xp:40,env:"home"},
    {title:"Appreciation Note",description:"Leave a written appreciation note for someone at work or school.",tips:"Post-it on their desk, signed or anonymous.",xp:35,env:"place"},
    {title:"New Friend",description:"Meet at least 1 new person today and exchange contacts.",tips:"Ask about shared interests.",xp:45,env:"outdoor"},
    {title:"Group Photo",description:"Take a group photo with family or friends.",tips:"Use timer, wait until everyone's ready.",xp:30,env:"home"},
    {title:"Neighbor Gift",description:"Bring something homemade to your neighbor (cookies, cake).",tips:"Even a simple recipe is very meaningful.",xp:45,env:"home"},
    {title:"Thank You Video",description:"Record a 30-second thank you video for someone who impacted you.",tips:"Be natural, it doesn't have to be perfect.",xp:40,env:"home"}
  ],
  creative: [
    {title:"60 Second Art",description:"Draw whatever's in front of you in 60 seconds.",tips:"Phone app or pen and paper, doesn't matter!",xp:30,env:"home"},
    {title:"Story Hunter",description:"Write a 5-sentence story from 3 random objects around you.",tips:"The more unrelated they are, the more fun.",xp:35,env:"home"},
    {title:"Sound Collage",description:"Record 5 different interesting sounds and create a sound collage.",tips:"10 seconds each is enough. Mix nature + city.",xp:35,env:"outdoor"},
    {title:"Shadow Artist",description:"Capture 3 interesting shadows and photograph them.",tips:"Noon creates the most dramatic shadows.",xp:30,env:"outdoor"},
    {title:"Haiku Writer",description:"Write 3 haikus (5-7-5 syllable rule).",tips:"Capture the moment, the feeling. Simplicity is power.",xp:35,env:"home"},
    {title:"Music Detective",description:"Shazam a song you hear at a café or store, listen to the full album.",tips:"Discovering new music is the best discovery.",xp:30,env:"place"},
    {title:"Photo Story",description:"Tell a story with a beginning and end using 5 photos.",tips:"Chronological order not required.",xp:40,env:"outdoor"},
    {title:"Off-Hand Drawing",description:"Draw a picture or write a paragraph with your non-dominant hand.",tips:"Laugh and keep going! Results don't matter.",xp:35,env:"home"},
    {title:"Nature Collage",description:"Create a composition on the ground with leaves, stones, flowers.",tips:"Symmetry and contrast give beautiful results.",xp:40,env:"outdoor"},
    {title:"Spotify Adventure",description:"Listen to 3 songs of different genres on Spotify Discover.",tips:"Give each song at least 1 minute.",xp:25,env:"home"},
    {title:"Mini Film",description:"Shoot a 30-second short film with your phone.",tips:"Simple scenario: beginning, middle, end.",xp:45,env:"any"},
    {title:"Poem Writer",description:"Turn a moment from today into a 4-line poem.",tips:"Rhyming isn't required, emotion matters.",xp:35,env:"home"},
    {title:"Food Photographer",description:"Photograph today's meal like a professional.",tips:"Natural light, 45-degree angle, clean background.",xp:25,env:"home"},
    {title:"Collage Artist",description:"Make a collage from old magazines, newspapers or prints.",tips:"Choose a theme: nature, city, emotions.",xp:40,env:"home"},
    {title:"Street Photographer",description:"Capture 'decisive moments' like Cartier-Bresson. Take 10 photos.",tips:"Be patient, wait for the moment.",xp:40,env:"outdoor"},
    {title:"Origami Master",description:"Learn an origami figure from YouTube and make it.",tips:"Paper crane is a classic start!",xp:35,env:"home"},
    {title:"Playlist Maker",description:"Choose a theme and create a 10-song playlist.",tips:"'Rainy day', 'motivation', 'night walk' etc.",xp:30,env:"home"},
    {title:"Miniature World",description:"Create a miniature scene with small objects and photograph it.",tips:"Close-up and low angle create magic.",xp:40,env:"home"},
    {title:"Daily Drawing",description:"Make a single drawing that represents today.",tips:"Stick figure is fine! It's about the meaning.",xp:30,env:"home"},
    {title:"Soundscape",description:"Record a 1-minute audio of where you are right now.",tips:"Close your eyes, note what you hear.",xp:30,env:"outdoor"}
  ],
  mindful: [
    {title:"5 Senses Meditation",description:"See 5 things, touch 4, hear 3, smell 2, taste 1.",tips:"Take 3 deep breaths before starting.",xp:30,env:"any"},
    {title:"Digital Detox",description:"Put your phone on airplane mode for 1 hour. No screens.",tips:"Leave the phone in another room.",xp:40,env:"home"},
    {title:"Gratitude Letter",description:"Write a heartfelt letter to someone you're grateful for.",tips:"Handwriting is more meaningful and personal.",xp:35,env:"home"},
    {title:"Cloud Watching",description:"Look at the sky for 15 min, find shapes in clouds.",tips:"Lie on the grass, put the phone away.",xp:30,env:"outdoor"},
    {title:"Silent Walk",description:"Walk for 20 min without headphones or music. Just listen.",tips:"Feel every step. This is walking meditation.",xp:35,env:"outdoor"},
    {title:"Breath Counter",description:"Count your breaths for 5 min. Try to reach 100.",tips:"If your mind wanders, gently bring it back.",xp:30,env:"home"},
    {title:"One Page Journal",description:"Write about today on one page, unfiltered.",tips:"Be honest. Nobody will read it.",xp:35,env:"home"},
    {title:"Slow Eating",description:"Eat one meal in 30 minutes. Chew each bite 20 times.",tips:"Phone and TV off. Just you and the food.",xp:40,env:"home"},
    {title:"Sunset Ritual",description:"Watch the entire sunset from start to finish.",tips:"High spot + warm drink = perfect.",xp:35,env:"outdoor"},
    {title:"Body Scan",description:"Scan every part of your body from toes to head for 10 min.",tips:"Search 'body scan meditation' on YouTube.",xp:30,env:"home"},
    {title:"Gratitude List",description:"Write 10 things you're grateful for today.",tips:"Small things count too: warm tea, sunshine.",xp:30,env:"home"},
    {title:"Nature Bath",description:"Spend 30 min in nature. Sit in a park, watch trees, listen to birds.",tips:"This is the Japanese 'shinrin-yoku' technique!",xp:40,env:"outdoor"},
    {title:"Morning Pages",description:"Write 3 pages of your thoughts right after waking up.",tips:"Don't edit, just let it flow.",xp:35,env:"home"},
    {title:"Single Task Hour",description:"Focus on only one task for 1 hour. No multitasking.",tips:"Silence your phone, turn off notifications.",xp:40,env:"home"},
    {title:"Tea Ceremony",description:"Brew your tea carefully, smell it, sip it. Be mindful of every step.",tips:"Use your favorite cup.",xp:30,env:"home"},
    {title:"Stargazing",description:"Look at the night sky for 10 min. Try to find constellations.",tips:"Away from city lights is ideal.",xp:35,env:"outdoor"},
    {title:"Body Gratitude",description:"Mentally thank each part of your body.",tips:"'Thank you hands, you did so much today.'",xp:30,env:"home"},
    {title:"Grounding",description:"Stand barefoot on grass or earth for 5 minutes.",tips:"Grounding technique: connect with nature.",xp:35,env:"outdoor"},
    {title:"Silence Time",description:"Do absolutely nothing for 15 min. Just sit and exist.",tips:"It will be hard but incredibly beneficial.",xp:40,env:"home"},
    {title:"Dream Journal",description:"Write down whatever dream you remember from last night.",tips:"Write immediately upon waking, dreams fade fast.",xp:25,env:"home"}
  ],
  food: [
    {title:"Unknown Flavor",description:"Buy something at the store you've never tried before.",tips:"Exotic fruits, different sauces, new spices!",xp:30,env:"outdoor"},
    {title:"Chef Mode",description:"Make a spontaneous meal from whatever's in your fridge. No recipe.",tips:"Your spice rack is your best friend.",xp:40,env:"home"},
    {title:"Coffee Ritual",description:"Prepare your coffee step by step with care. Enjoy every stage.",tips:"Try pour-over, French press, or Turkish coffee.",xp:30,env:"home"},
    {title:"Street Food",description:"Buy something you've never tried from a street vendor.",tips:"Feel the atmosphere, chat with the vendor.",xp:30,env:"outdoor"},
    {title:"World Cuisine",description:"Try a dish from a different country's cuisine today.",tips:"Indian, Thai, Korean, Mexican, Japanese!",xp:40,env:"place"},
    {title:"Childhood Flavor",description:"Make your favorite childhood dish yourself.",tips:"Ask your parents for the recipe!",xp:35,env:"home"},
    {title:"Zero Waste Chef",description:"Make a creative dish with ingredients about to expire.",tips:"Soup, omelet, and pasta are lifesavers.",xp:35,env:"home"},
    {title:"Dessert Experiment",description:"Try making a simple dessert you've never made before.",tips:"Mug cake is ready in 5 minutes!",xp:35,env:"home"},
    {title:"Spice Adventure",description:"Cook with a spice you've never used before.",tips:"Try turmeric, cumin, sumac, or ginger.",xp:30,env:"home"},
    {title:"Tea Tasting",description:"Brew 3 different teas, compare their aromas and flavors.",tips:"Use small cups, take notes.",xp:25,env:"home"},
    {title:"Smoothie Artist",description:"Make a creative smoothie with 3+ ingredients.",tips:"Banana + spinach + mango = beginner level.",xp:30,env:"home"},
    {title:"Bread Maker",description:"Bake simple bread or flatbread at home.",tips:"Flour, water, yeast, salt. That simple!",xp:45,env:"home"},
    {title:"Picnic Prep",description:"Prepare a picnic basket, eat at a park or balcony.",tips:"Sandwiches, fruit, nuts, and a thermos of tea.",xp:35,env:"outdoor"},
    {title:"Breakfast Chef",description:"Prepare a fancy breakfast you don't normally make.",tips:"Try eggs benedict, pancakes, or pastries.",xp:35,env:"home"},
    {title:"Sauce Master",description:"Make a sauce from scratch (pesto, salsa, hummus, etc).",tips:"Blender or mortar, both work.",xp:35,env:"home"},
    {title:"Fermentation Adventure",description:"Start pickles, yogurt, or sourdough.",tips:"Easiest: cucumber pickles. Water + salt + cucumbers.",xp:40,env:"home"},
    {title:"Food Photography",description:"Photograph today's meal Instagram-worthy.",tips:"Natural light + white background + close-up.",xp:25,env:"home"},
    {title:"Chocolate Tasting",description:"Try 3 different chocolates (dark, milk, white). Take notes.",tips:"Compare cocoa percentages.",xp:30,env:"home"},
    {title:"International Snack",description:"Find a foreign snack at the store and try it.",tips:"Asian grocery stores are treasure troves!",xp:30,env:"outdoor"},
    {title:"Lemonade Master",description:"Make a non-classic lemonade (lavender, mint, ginger).",tips:"Fresh ingredients make all the difference.",xp:30,env:"home"}
  ],
  fitness: [
    {title:"1000 Extra Steps",description:"Add 1000 extra steps to your day.",tips:"A 15-min walk during lunch break is enough.",xp:30,env:"outdoor"},
    {title:"Park Workout",description:"Do 10 push-ups, 20 squats, 30-sec plank at a park.",tips:"Use a park bench!",xp:40,env:"outdoor"},
    {title:"Stretch Session",description:"Stretch your whole body for 15 minutes.",tips:"Search '15 min full body stretch' on YouTube.",xp:30,env:"home"},
    {title:"Dance Party",description:"Play your 3 favorite songs and dance like nobody's watching!",tips:"Close the curtains, nobody's looking!",xp:35,env:"home"},
    {title:"Stair Climber",description:"Take stairs instead of elevator. Climb at least 10 floors.",tips:"Track with a step counter.",xp:40,env:"outdoor"},
    {title:"7 Minute Workout",description:"Do the scientific 7-minute HIIT program.",tips:"Only 7 min but the effect lasts hours!",xp:35,env:"home"},
    {title:"Walk & Talk",description:"Invite a friend for a walk. Exercise and chat.",tips:"30 min is enough, café stop is a bonus!",xp:35,env:"outdoor"},
    {title:"Morning Routine",description:"Set an alarm tomorrow and do 5 min of exercise.",tips:"10 squats, 10 jumping jacks, 10 lunges.",xp:40,env:"home"},
    {title:"Balance Master",description:"Stand on one foot for 30 seconds. Try both sides.",tips:"Focus on one point, balance will come.",xp:30,env:"home"},
    {title:"Home Circuit",description:"Keep moving around your home for 5 minutes.",tips:"Light pace, turn on some music!",xp:30,env:"home"},
    {title:"Bike Ride",description:"Ride a bike for 30 minutes. Plan your route.",tips:"No bike? Check rental stations.",xp:45,env:"outdoor"},
    {title:"Yoga Beginner",description:"Do a 15-min beginner yoga session from YouTube.",tips:"'Yoga with Adriene' is a great resource.",xp:35,env:"home"},
    {title:"Run Attempt",description:"Run 5 min, walk 2 min. Repeat 3 sets.",tips:"Perfect pace for beginners.",xp:40,env:"outdoor"},
    {title:"Jump Rope",description:"Jump rope 100 times. Take breaks if needed.",tips:"No rope? Pretend jump, seriously!",xp:35,env:"home"},
    {title:"Plank Challenge",description:"Do a total of 3 min of planks. Split with breaks.",tips:"30 sec plank + 15 sec rest x 4 sets.",xp:35,env:"home"},
    {title:"Swimming",description:"Go to a pool or the sea, swim for 30 min.",tips:"Mix freestyle + backstroke.",xp:45,env:"place"},
    {title:"Wall Sit",description:"Back against the wall, hold a wall sit for 1 minute.",tips:"Knees at 90 degrees, back straight.",xp:30,env:"home"},
    {title:"Evening Walk",description:"Take a 20-min walk after dinner.",tips:"Great for digestion and sleep quality.",xp:30,env:"outdoor"},
    {title:"Workout Class",description:"Try a new workout video on YouTube (kickbox, pilates, etc).",tips:"You don't have to be perfect the first time.",xp:40,env:"home"},
    {title:"Nature Hike",description:"Hike for 45+ minutes in the nearest nature area.",tips:"Bring water and snacks!",xp:45,env:"outdoor"}
  ]
};
